Create is-cron-editor component
IntelStudios/is-components-ngx pull request #3
Opened 2019-06-24 09:46 UTC by esoadamo

2019-06-25 08:35 UTC, lzoubek requested changes

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.component.ts
> +    if (!cronExpression) {
Can you rewrite this and not force any default cron?

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.component.ts
> +  }]
Also please implement `Validator` interface. Angular forms will call it and mark your control invalid in case there is invalid cron expression

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.component.html
> +<div (click)="onTouched()" style="display: flex;justify-content: center;font-size: 18px;">
Please use classes instead of inline styles

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.component.html
> +  <input type="text" [formControl]="cronExpressionControl">
all input tags should have `form-control` css class

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.component.css
> +.two-digit-number {
Please use .scss instead of css

2019-06-25 08:35 UTC, lzoubek commented on projects/is-cron-editor/src/lib/is-cron-editor.service.ts
> +import { Injectable } from '@angular/core';
Please remove this unused service

2019-06-25 17:03 UTC, esoadamo commented
It should be all fixed now

2019-06-28 11:59 UTC, lzoubek commented
Merged manually with few changes

2019-06-28 11:59 UTC, closed without merging